name: tutorial
channels:
- defaults
- conda-forge
dependencies:
  - python=3.5*
  - ipywidgets
  - pandas
  - bokeh
  - matplotlib
  - scipy
  - scikit-learn
  - scikit-image
  - sympy
  - cython
  - cloudpickle
  - dill
  - numba
  - h5py
  - dask
  - pymongo
  - cytoolz
  - tifffile
  - lmfit
  - openpyxl
  - xlrd
  - pip:
    - pyepics
    - mongoquery
    - attrs
    - ipympl
    - requests
    - boltons
    - tzlocal
    - jupyter-emacskeys
    - pims
    - rise
    - bluesky
    - ophyd
    - databroker
    - oscars
    - git+https://github.com/NSLS-II/amostra#egg=amostra
